version: "3"

services:
  geth:
    container_name: geth
    image: "celer-network/geth"
    ports:
      - "8545-8546:8545-8546"
    volumes:
      - ./build:/geth/bin:Z
      - ./docker-volumes/geth-env:/geth/env:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.1

  sgnnode0:
    container_name: sgnnode0
    image: "celer-network/sgnnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - LOG=${LOG:-sgn.log}
    volumes:
      # - ./build:/sgn/bin:Z
      - ./docker-volumes/node0:/sgn/env:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  sgnnode1:
    container_name: sgnnode1
    image: "celer-network/sgnnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - LOG=${LOG:-sgn.log}
    volumes:
      - ./build:/sgn/bin:Z
      - ./docker-volumes/node1:/sgn/env:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  sgnnode2:
    container_name: sgnnode2
    image: "celer-network/sgnnode"
    environment:
      - LOG=${LOG:-sgn.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/sgn/bin:Z
      - ./docker-volumes/node2:/sgn/env:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
