// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sgn.proto

package sgn

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Next Tag: 3
// This is a generic multi-sig message for DPoS contract to validate any
// types of request messages
type MultiSigMessage struct {
	// serialized message
	Msg                  []byte   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Sigs                 [][]byte `protobuf:"bytes,2,rep,name=sigs,proto3" json:"sigs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiSigMessage) Reset()         { *m = MultiSigMessage{} }
func (m *MultiSigMessage) String() string { return proto.CompactTextString(m) }
func (*MultiSigMessage) ProtoMessage()    {}
func (*MultiSigMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce30e4acb09a2956, []int{0}
}

func (m *MultiSigMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiSigMessage.Unmarshal(m, b)
}
func (m *MultiSigMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiSigMessage.Marshal(b, m, deterministic)
}
func (m *MultiSigMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiSigMessage.Merge(m, src)
}
func (m *MultiSigMessage) XXX_Size() int {
	return xxx_messageInfo_MultiSigMessage.Size(m)
}
func (m *MultiSigMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiSigMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MultiSigMessage proto.InternalMessageInfo

func (m *MultiSigMessage) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *MultiSigMessage) GetSigs() [][]byte {
	if m != nil {
		return m.Sigs
	}
	return nil
}

// Next Tag: 3
type PenaltyRequest struct {
	// serialized Penalty message
	Penalty              []byte   `protobuf:"bytes,1,opt,name=penalty,proto3" json:"penalty,omitempty"`
	Sigs                 [][]byte `protobuf:"bytes,2,rep,name=sigs,proto3" json:"sigs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PenaltyRequest) Reset()         { *m = PenaltyRequest{} }
func (m *PenaltyRequest) String() string { return proto.CompactTextString(m) }
func (*PenaltyRequest) ProtoMessage()    {}
func (*PenaltyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce30e4acb09a2956, []int{1}
}

func (m *PenaltyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PenaltyRequest.Unmarshal(m, b)
}
func (m *PenaltyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PenaltyRequest.Marshal(b, m, deterministic)
}
func (m *PenaltyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PenaltyRequest.Merge(m, src)
}
func (m *PenaltyRequest) XXX_Size() int {
	return xxx_messageInfo_PenaltyRequest.Size(m)
}
func (m *PenaltyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PenaltyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PenaltyRequest proto.InternalMessageInfo

func (m *PenaltyRequest) GetPenalty() []byte {
	if m != nil {
		return m.Penalty
	}
	return nil
}

func (m *PenaltyRequest) GetSigs() [][]byte {
	if m != nil {
		return m.Sigs
	}
	return nil
}

// Next Tag: 3
type RewardRequest struct {
	// serialized Reward message
	Reward               []byte   `protobuf:"bytes,1,opt,name=reward,proto3" json:"reward,omitempty"`
	Sigs                 [][]byte `protobuf:"bytes,2,rep,name=sigs,proto3" json:"sigs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RewardRequest) Reset()         { *m = RewardRequest{} }
func (m *RewardRequest) String() string { return proto.CompactTextString(m) }
func (*RewardRequest) ProtoMessage()    {}
func (*RewardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce30e4acb09a2956, []int{2}
}

func (m *RewardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RewardRequest.Unmarshal(m, b)
}
func (m *RewardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RewardRequest.Marshal(b, m, deterministic)
}
func (m *RewardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardRequest.Merge(m, src)
}
func (m *RewardRequest) XXX_Size() int {
	return xxx_messageInfo_RewardRequest.Size(m)
}
func (m *RewardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RewardRequest proto.InternalMessageInfo

func (m *RewardRequest) GetReward() []byte {
	if m != nil {
		return m.Reward
	}
	return nil
}

func (m *RewardRequest) GetSigs() [][]byte {
	if m != nil {
		return m.Sigs
	}
	return nil
}

// Next Tag: 6
type Penalty struct {
	Nonce                uint64            `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ExpireTime           uint64            `protobuf:"varint,2,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	ValidatorAddress     []byte            `protobuf:"bytes,3,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	PenalizedDelegators  []*AccountAmtPair `protobuf:"bytes,4,rep,name=penalized_delegators,json=penalizedDelegators,proto3" json:"penalized_delegators,omitempty"`
	Beneficiaries        []*AccountAmtPair `protobuf:"bytes,5,rep,name=beneficiaries,proto3" json:"beneficiaries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Penalty) Reset()         { *m = Penalty{} }
func (m *Penalty) String() string { return proto.CompactTextString(m) }
func (*Penalty) ProtoMessage()    {}
func (*Penalty) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce30e4acb09a2956, []int{3}
}

func (m *Penalty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Penalty.Unmarshal(m, b)
}
func (m *Penalty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Penalty.Marshal(b, m, deterministic)
}
func (m *Penalty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Penalty.Merge(m, src)
}
func (m *Penalty) XXX_Size() int {
	return xxx_messageInfo_Penalty.Size(m)
}
func (m *Penalty) XXX_DiscardUnknown() {
	xxx_messageInfo_Penalty.DiscardUnknown(m)
}

var xxx_messageInfo_Penalty proto.InternalMessageInfo

func (m *Penalty) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Penalty) GetExpireTime() uint64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *Penalty) GetValidatorAddress() []byte {
	if m != nil {
		return m.ValidatorAddress
	}
	return nil
}

func (m *Penalty) GetPenalizedDelegators() []*AccountAmtPair {
	if m != nil {
		return m.PenalizedDelegators
	}
	return nil
}

func (m *Penalty) GetBeneficiaries() []*AccountAmtPair {
	if m != nil {
		return m.Beneficiaries
	}
	return nil
}

// Next Tag: 3
type AccountAmtPair struct {
	Account              []byte   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Amt                  []byte   `protobuf:"bytes,2,opt,name=amt,proto3" json:"amt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountAmtPair) Reset()         { *m = AccountAmtPair{} }
func (m *AccountAmtPair) String() string { return proto.CompactTextString(m) }
func (*AccountAmtPair) ProtoMessage()    {}
func (*AccountAmtPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce30e4acb09a2956, []int{4}
}

func (m *AccountAmtPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountAmtPair.Unmarshal(m, b)
}
func (m *AccountAmtPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountAmtPair.Marshal(b, m, deterministic)
}
func (m *AccountAmtPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountAmtPair.Merge(m, src)
}
func (m *AccountAmtPair) XXX_Size() int {
	return xxx_messageInfo_AccountAmtPair.Size(m)
}
func (m *AccountAmtPair) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountAmtPair.DiscardUnknown(m)
}

var xxx_messageInfo_AccountAmtPair proto.InternalMessageInfo

func (m *AccountAmtPair) GetAccount() []byte {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *AccountAmtPair) GetAmt() []byte {
	if m != nil {
		return m.Amt
	}
	return nil
}

// Next Tag: 4
type Reward struct {
	Receiver                []byte   `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	CumulativeMiningReward  []byte   `protobuf:"bytes,2,opt,name=cumulative_mining_reward,json=cumulativeMiningReward,proto3" json:"cumulative_mining_reward,omitempty"`
	CumulativeServiceReward []byte   `protobuf:"bytes,3,opt,name=cumulative_service_reward,json=cumulativeServiceReward,proto3" json:"cumulative_service_reward,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Reward) Reset()         { *m = Reward{} }
func (m *Reward) String() string { return proto.CompactTextString(m) }
func (*Reward) ProtoMessage()    {}
func (*Reward) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce30e4acb09a2956, []int{5}
}

func (m *Reward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reward.Unmarshal(m, b)
}
func (m *Reward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reward.Marshal(b, m, deterministic)
}
func (m *Reward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reward.Merge(m, src)
}
func (m *Reward) XXX_Size() int {
	return xxx_messageInfo_Reward.Size(m)
}
func (m *Reward) XXX_DiscardUnknown() {
	xxx_messageInfo_Reward.DiscardUnknown(m)
}

var xxx_messageInfo_Reward proto.InternalMessageInfo

func (m *Reward) GetReceiver() []byte {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *Reward) GetCumulativeMiningReward() []byte {
	if m != nil {
		return m.CumulativeMiningReward
	}
	return nil
}

func (m *Reward) GetCumulativeServiceReward() []byte {
	if m != nil {
		return m.CumulativeServiceReward
	}
	return nil
}

var E_Soltype = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1004,
	Name:          "sgn.soltype",
	Tag:           "bytes,1004,opt,name=soltype",
	Filename:      "sgn.proto",
}

func init() {
	proto.RegisterType((*MultiSigMessage)(nil), "sgn.MultiSigMessage")
	proto.RegisterType((*PenaltyRequest)(nil), "sgn.PenaltyRequest")
	proto.RegisterType((*RewardRequest)(nil), "sgn.RewardRequest")
	proto.RegisterType((*Penalty)(nil), "sgn.Penalty")
	proto.RegisterType((*AccountAmtPair)(nil), "sgn.AccountAmtPair")
	proto.RegisterType((*Reward)(nil), "sgn.Reward")
	proto.RegisterExtension(E_Soltype)
}

func init() { proto.RegisterFile("sgn.proto", fileDescriptor_ce30e4acb09a2956) }

var fileDescriptor_ce30e4acb09a2956 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x95, 0xba, 0x8d, 0xe9, 0xf4, 0x0f, 0x65, 0x5b, 0x15, 0x83, 0x40, 0x44, 0x11, 0xaa,
	0x72, 0xc1, 0x91, 0x8a, 0xa0, 0xfc, 0x91, 0x2a, 0xa5, 0xaa, 0x72, 0x8b, 0xa8, 0xdc, 0x9e, 0xb8,
	0x44, 0x9b, 0xf5, 0x74, 0x19, 0x61, 0xef, 0x9a, 0xdd, 0x75, 0x4a, 0x79, 0x38, 0x1e, 0x86, 0x33,
	0x8f, 0xc0, 0x01, 0xd9, 0x6b, 0xa7, 0x44, 0x0d, 0xb7, 0xd9, 0x6f, 0x7e, 0xdf, 0x37, 0xf2, 0xce,
	0x1a, 0x36, 0xad, 0x54, 0x71, 0x61, 0xb4, 0xd3, 0x2c, 0xb0, 0x52, 0x3d, 0xed, 0x49, 0xad, 0x65,
	0x86, 0xc3, 0x5a, 0x9a, 0x95, 0xd7, 0xc3, 0x14, 0xad, 0x30, 0x54, 0x38, 0x6d, 0x3c, 0xd6, 0x3f,
	0x81, 0x87, 0x93, 0x32, 0x73, 0x74, 0x49, 0x72, 0x82, 0xd6, 0x72, 0x89, 0x6c, 0x0f, 0x82, 0xdc,
	0xca, 0xa8, 0xd3, 0xeb, 0x0c, 0xb6, 0x93, 0xaa, 0x64, 0x0c, 0xd6, 0x2d, 0x49, 0x1b, 0xad, 0xf5,
	0x82, 0xc1, 0x76, 0x52, 0xd7, 0xfd, 0x53, 0xd8, 0xbd, 0x40, 0xc5, 0x33, 0x77, 0x9b, 0xe0, 0xb7,
	0x12, 0xad, 0x63, 0x11, 0x84, 0x85, 0x57, 0x1a, 0x6f, 0x7b, 0x5c, 0xe9, 0xff, 0x08, 0x3b, 0x09,
	0xde, 0x70, 0x93, 0xb6, 0xf6, 0x43, 0xe8, 0x9a, 0x5a, 0x68, 0xdc, 0xcd, 0x69, 0xa5, 0xf9, 0x4f,
	0x07, 0xc2, 0x66, 0x3a, 0x3b, 0x80, 0x0d, 0xa5, 0x95, 0xc0, 0xda, 0xb6, 0x9e, 0xf8, 0x03, 0x7b,
	0x01, 0x5b, 0xf8, 0xbd, 0x20, 0x83, 0x53, 0x47, 0x39, 0x46, 0x6b, 0x75, 0x0f, 0xbc, 0x74, 0x45,
	0x39, 0xb2, 0x13, 0x78, 0x34, 0xe7, 0x19, 0xa5, 0xdc, 0x69, 0x33, 0xe5, 0x69, 0x6a, 0xd0, 0xda,
	0x28, 0xa8, 0x26, 0x9f, 0xc1, 0xaf, 0xd3, 0xb0, 0x51, 0x92, 0xbd, 0x05, 0x34, 0xf2, 0x0a, 0x1b,
	0xc3, 0x41, 0xfd, 0x5d, 0xf4, 0x03, 0xd3, 0x69, 0x8a, 0x19, 0xca, 0xaa, 0x6b, 0xa3, 0xf5, 0x5e,
	0x30, 0xd8, 0x3a, 0xde, 0x8f, 0xab, 0x15, 0x8c, 0x84, 0xd0, 0xa5, 0x72, 0xa3, 0xdc, 0x5d, 0x70,
	0x32, 0xc9, 0xfe, 0xc2, 0x70, 0xbe, 0xe0, 0xd9, 0x7b, 0xd8, 0x99, 0xa1, 0xc2, 0x6b, 0x12, 0xc4,
	0x0d, 0xa1, 0x8d, 0x36, 0xfe, 0x1f, 0xb0, 0x4c, 0xf6, 0xaf, 0x60, 0x77, 0x19, 0x60, 0x2f, 0x21,
	0xe4, 0x5e, 0xf1, 0xb7, 0xb7, 0xf4, 0x0d, 0x6d, 0x8b, 0x3d, 0x83, 0x80, 0xe7, 0xae, 0xbe, 0x0c,
	0x4f, 0x94, 0xa4, 0xdc, 0xf1, 0x9b, 0xb7, 0x49, 0x25, 0xf7, 0x7f, 0x76, 0xa0, 0xeb, 0x57, 0xc2,
	0x8e, 0xe0, 0x81, 0x41, 0x81, 0x34, 0x47, 0xb3, 0x22, 0x6f, 0xd1, 0x63, 0xe7, 0x10, 0x89, 0x32,
	0x2f, 0x33, 0xee, 0x68, 0x8e, 0xd3, 0x9c, 0x14, 0x29, 0x39, 0x6d, 0xb6, 0x78, 0x7f, 0xca, 0xe1,
	0x1d, 0x3b, 0xa9, 0xd1, 0x66, 0xda, 0x18, 0x9e, 0xfc, 0x93, 0x62, 0xd1, 0xcc, 0x49, 0x60, 0x1b,
	0x13, 0xdc, 0x8b, 0x79, 0x7c, 0x07, 0x5f, 0x7a, 0xd6, 0xe7, 0x7c, 0x78, 0x07, 0xa1, 0xd5, 0x99,
	0xbb, 0x2d, 0x90, 0x3d, 0x8f, 0xfd, 0xcb, 0x8f, 0xdb, 0x97, 0x1f, 0x8f, 0x09, 0xb3, 0xf4, 0x53,
	0xe1, 0x48, 0x2b, 0x1b, 0xfd, 0x0e, 0x7b, 0x9d, 0xc1, 0x66, 0xd2, 0xe2, 0x67, 0x83, 0xcf, 0x47,
	0x92, 0xdc, 0x97, 0x72, 0x16, 0x0b, 0x9d, 0x0f, 0x05, 0x66, 0x68, 0x5e, 0x29, 0x74, 0x37, 0xda,
	0x7c, 0x1d, 0x5a, 0xa9, 0xfc, 0xff, 0x53, 0x55, 0xb3, 0x6e, 0x5d, 0xbe, 0xfe, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x20, 0xce, 0x84, 0xe4, 0x6a, 0x03, 0x00, 0x00,
}
