// Code generated by protoc-gen-go. DO NOT EDIT.
// source: seal.proto

package seal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactorLog struct {
	TxHash               string            `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	MsgNum               uint32            `protobuf:"varint,2,opt,name=msg_num,json=msgNum,proto3" json:"msg_num,omitempty"`
	MsgType              map[string]uint32 `protobuf:"bytes,3,rep,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Error                []string          `protobuf:"bytes,4,rep,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TransactorLog) Reset()         { *m = TransactorLog{} }
func (m *TransactorLog) String() string { return proto.CompactTextString(m) }
func (*TransactorLog) ProtoMessage()    {}
func (*TransactorLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_a02c8d155741ea4f, []int{0}
}

func (m *TransactorLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactorLog.Unmarshal(m, b)
}
func (m *TransactorLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactorLog.Marshal(b, m, deterministic)
}
func (m *TransactorLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactorLog.Merge(m, src)
}
func (m *TransactorLog) XXX_Size() int {
	return xxx_messageInfo_TransactorLog.Size(m)
}
func (m *TransactorLog) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactorLog.DiscardUnknown(m)
}

var xxx_messageInfo_TransactorLog proto.InternalMessageInfo

func (m *TransactorLog) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *TransactorLog) GetMsgNum() uint32 {
	if m != nil {
		return m.MsgNum
	}
	return 0
}

func (m *TransactorLog) GetMsgType() map[string]uint32 {
	if m != nil {
		return m.MsgType
	}
	return nil
}

func (m *TransactorLog) GetError() []string {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*TransactorLog)(nil), "seal.TransactorLog")
	proto.RegisterMapType((map[string]uint32)(nil), "seal.TransactorLog.MsgTypeEntry")
}

func init() { proto.RegisterFile("seal.proto", fileDescriptor_a02c8d155741ea4f) }

var fileDescriptor_a02c8d155741ea4f = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x4e, 0x4d, 0xcc,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x2e, 0x30, 0x72, 0xf1, 0x86,
	0x14, 0x25, 0xe6, 0x15, 0x27, 0x26, 0x97, 0xe4, 0x17, 0xf9, 0xe4, 0xa7, 0x0b, 0x89, 0x73, 0xb1,
	0x97, 0x54, 0xc4, 0x67, 0x24, 0x16, 0x67, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xb1, 0x95,
	0x54, 0x78, 0x24, 0x16, 0x67, 0x80, 0x24, 0x72, 0x8b, 0xd3, 0xe3, 0xf3, 0x4a, 0x73, 0x25, 0x98,
	0x14, 0x18, 0x35, 0x78, 0x83, 0xd8, 0x72, 0x8b, 0xd3, 0xfd, 0x4a, 0x73, 0x85, 0xac, 0xb9, 0x38,
	0x40, 0x12, 0x25, 0x95, 0x05, 0xa9, 0x12, 0xcc, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x0a, 0x7a, 0x60,
	0x8b, 0x50, 0x0c, 0xd6, 0xf3, 0x2d, 0x4e, 0x0f, 0xa9, 0x2c, 0x48, 0x75, 0xcd, 0x2b, 0x29, 0xaa,
	0x0c, 0x02, 0x19, 0x05, 0xe2, 0x09, 0x89, 0x70, 0xb1, 0xa6, 0x16, 0x15, 0xe5, 0x17, 0x49, 0xb0,
	0x28, 0x30, 0x6b, 0x70, 0x06, 0x41, 0x38, 0x52, 0x56, 0x5c, 0x3c, 0xc8, 0xca, 0x85, 0x04, 0xb8,
	0x98, 0xb3, 0x53, 0x2b, 0xa1, 0x0e, 0x02, 0x31, 0x41, 0xfa, 0xca, 0x12, 0x73, 0x4a, 0x53, 0xa1,
	0x6e, 0x81, 0x70, 0xac, 0x98, 0x2c, 0x18, 0x93, 0xd8, 0xc0, 0xfe, 0x33, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x13, 0x50, 0x95, 0xd2, 0xed, 0x00, 0x00, 0x00,
}
