copy-config:
	cp ./.sgn/config/genesis.json ~/.sgn/config/genesis.json
	cp ./.sgn/config/config.toml ~/.sgn/config/config.toml
	mkdir -p ~/.sgncli/config/ && cp ./.sgncli/config/config.toml ~/.sgncli/config/config.toml
