copy-config:
	rm -rf ~/.sgn/config/ && mkdir -p ~/.sgn/config/
	rm -rf ~/.sgncli/config/ && mkdir -p ~/.sgncli/config/
	cp ./.sgn/config/genesis.json ~/.sgn/config/genesis.json
	cp ./.sgn/config/config.toml ~/.sgn/config/config.toml
	cp ./.sgncli/config/config.toml ~/.sgncli/config/config.toml
