copy-config:
	mkdir -p ~/.sgn/config/ && cp ./.sgn/config/genesis.json ~/.sgn/config/genesis.json
	mkdir -p ~/.sgn/config/ && cp ./.sgn/config/config.toml ~/.sgn/config/config.toml
	mkdir -p ~/.sgncli/config/ && cp ./.sgncli/config/config.toml ~/.sgncli/config/config.toml
